/*
 * File: SeqCheckerPanel.js
 * Date: Tue Nov 30 2010 16:50:46 GMT-0800 (PST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

SeqCheckerPanel = Ext.extend(SeqCheckerPanelUi, {
    initComponent: function() {
        SeqCheckerPanel.superclass.initComponent.call(this);
    }
});
