/*
 * File: StartStopStore.js
 * Date: Fri Feb 04 2011 02:39:54 GMT-0800 (PST)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

StartStopStore = Ext.extend(Ext.data.ArrayStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        StartStopStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'startStopStore',
            idIndex: 0,
            autoLoad: true,
            fields: [
                {
                    name: 'serialNum',
                    allowBlank: false,
                    type: 'int'
                },
                {
                    name: 'start',
                    allowBlank: false,
                    type: 'string'
                },
                {
                    name: 'stop',
                    allowBlank: false,
                    type: 'string'
                }
            ]
        }, cfg));
    }
});
new StartStopStore();