/*
 * File: PlanStore.js
 * Date: Tue Nov 30 2010 23:20:44 GMT-0800 (PST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

PlanStore = Ext.extend(Ext.data.ArrayStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        PlanStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'planStore',
            autoLoad: true,
            idIndex: 0,
            restful: true,
            data: [
                [
                    0,
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    ''
                ],
                [
                    1,
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    ''
                ],
                [
                    2,
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    ''
                ],
                [
                    3,
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    ''
                ],
                [
                    4,
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    ''
                ],
                [
                    5,
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    ''
                ],
                [
                    6,
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    ''
                ],
                [
                    7,
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    ''
                ],
                [
                    8,
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    ''
                ],
                [
                    9,
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    ''
                ],
                [
                    10,
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    ''
                ],
                [
                    11,
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    ''
                ],
                [
                    12,
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    ''
                ],
                [
                    13,
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    ''
                ],
                [
                    14,
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    ''
                ],
                [
                    15,
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    ''
                ],
                [
                    16,
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    ''
                ],
                [
                    17,
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    ''
                ],
                [
                    18,
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    ''
                ],
                [
                    19,
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    ''
                ]
            ],
            fields: [
                {
                    name: 'serialNumber',
                    type: 'int',
                    allowBlank: false
                },
                {
                    name: 'positionI',
                    type: 'string'
                },
                {
                    name: 'positionII',
                    type: 'string'
                },
                {
                    name: 'positionIII',
                    type: 'string'
                },
                {
                    name: 'positionIV',
                    type: 'string'
                },
                {
                    name: 'positionV',
                    type: 'string'
                },
                {
                    name: 'positionVI',
                    type: 'string'
                },
                {
                    name: 'positionVII',
                    type: 'string'
                },
                {
                    name: 'positionVIII',
                    type: 'string'
                }
            ]
        }, cfg));
    }
});
new PlanStore();