/*
 * File: RefineStdStore.js
 * Date: Tue Nov 30 2010 20:50:38 GMT-0800 (PST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

RefineStdStore = Ext.extend(Ext.data.ArrayStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        RefineStdStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'refineStdStore',
            autoLoad: true,
            idIndex: 0,
            data: [
                [
                    "biofab",
                    "BIOFAB"
                ],
                [
                    'bbf10',
                    'BBF RFC 10'
                ],
                [
                    'bbf12',
                    'BBF RFC 12'
                ],
                [
                    'bbf21',
                    'BBF RFC 21'
                ],
                [
                    'bbf25',
                    'BBF RFC 25'
                ]
            ],
            fields: [
                {
                    name: 'id',
                    allowBlank: false,
                    type: 'string'
                },
                {
                    name: 'name',
                    allowBlank: false,
                    type: 'string'
                }
            ]
        }, cfg));
    }
});
new RefineStdStore();