/*
 * File: SeqDesignerPanel.js
 * Date: Tue Nov 30 2010 20:50:21 GMT-0800 (PST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

SeqDesignerPanel = Ext.extend(SeqDesignerPanelUi, {
    initComponent: function() {
        SeqDesignerPanel.superclass.initComponent.call(this);
    }
});
