/*
 * File: AssemblerPanel.ui.js
 * Date: Tue Nov 30 2010 23:20:44 GMT-0800 (PST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

AssemblerPanelUi = Ext.extend(Ext.Panel, {
    title: 'Assembler',
    layout: 'border',
    closable: true,
    id: 'assemblerPanel',
    initComponent: function() {
        this.items = [
            {
                xtype: 'tabpanel',
                activeTab: 0,
                region: 'center',
                ref: 'centerTabPanel',
                id: 'centerTabPanel',
                items: [
                    {
                        xtype: 'panel',
                        title: 'Plan',
                        layout: 'border',
                        ref: '../planPanel',
                        id: 'planPanel',
                        items: [
                            {
                                xtype: 'editorgrid',
                                store: 'planStore',
                                enableDragDrop: true,
                                columnLines: true,
                                enableColumnMove: false,
                                enableColumnHide: false,
                                region: 'center',
                                split: true,
                                ref: '../../planGridPanel',
                                id: 'planGridPanel',
                                selModel: new Ext.grid.CellSelectionModel({

                                }),
                                columns: [
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'positionI',
                                        header: 'Position I',
                                        sortable: false,
                                        width: 125,
                                        align: 'center',
                                        hideable: false,
                                        editor: {
                                            xtype: 'textfield'
                                        }
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'positionII',
                                        header: 'Position II',
                                        sortable: false,
                                        width: 125,
                                        align: 'center',
                                        hideable: false,
                                        editor: {
                                            xtype: 'textfield'
                                        }
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'positionIII',
                                        header: 'Position III',
                                        sortable: false,
                                        width: 125,
                                        align: 'center',
                                        hideable: false,
                                        editor: {
                                            xtype: 'textfield'
                                        }
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'positioniV',
                                        header: 'Position IV',
                                        sortable: false,
                                        width: 125,
                                        align: 'center',
                                        hideable: false,
                                        editor: {
                                            xtype: 'textfield'
                                        }
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'positionV',
                                        header: 'Position V',
                                        sortable: false,
                                        width: 125,
                                        align: 'center',
                                        hideable: false,
                                        editor: {
                                            xtype: 'textfield'
                                        }
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'positionVI',
                                        header: 'Position VI',
                                        sortable: false,
                                        width: 125,
                                        align: 'center',
                                        hideable: false,
                                        editor: {
                                            xtype: 'textfield'
                                        }
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'positionVII',
                                        header: 'Position VII',
                                        sortable: false,
                                        width: 125,
                                        align: 'center',
                                        hideable: false,
                                        editor: {
                                            xtype: 'textfield'
                                        }
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'positionVIII',
                                        header: 'Position VIII',
                                        sortable: false,
                                        width: 125,
                                        align: 'center',
                                        hideable: false,
                                        editor: {
                                            xtype: 'textfield'
                                        }
                                    }
                                ]
                            },
                            {
                                xtype: 'grid',
                                store: 'assemblyBackboneStore',
                                region: 'west',
                                width: 125,
                                split: true,
                                ref: '../../backbonesGridPanel',
                                id: 'backbonesGridPanel',
                                columns: [
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'id',
                                        header: 'Backbones',
                                        sortable: true,
                                        width: 125,
                                        editable: false,
                                        align: 'center'
                                    }
                                ]
                            },
                            {
                                xtype: 'textarea',
                                readOnly: true,
                                emptyText: 'Select a bin to display the annealed insert.',
                                width: 100,
                                split: true,
                                region: 'south',
                                height: 175,
                                style: '{font-family: \'courier\' }',
                                ref: '../../annealingResultTextArea',
                                id: 'annealingResultTextArea'
                            }
                        ],
                        tbar: {
                            xtype: 'toolbar',
                            ref: '../../planTabToolbar',
                            id: 'planTabToolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Assemble',
                                    ref: '../../../assembleButton',
                                    id: 'assembleButton'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Empty Bin',
                                    ref: '../../../emptyBinButton',
                                    id: 'emptyBinButton'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'CSV',
                                    disabled: true
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'BIOFAB',
                                    disabled: true,
                                    ref: '../../../planToDBButton',
                                    id: 'planToDBButton'
                                }
                            ]
                        }
                    },
                    {
                        xtype: 'panel',
                        title: 'Constructs',
                        layout: 'border',
                        ref: '../constructsPanel',
                        id: 'constructsPanel',
                        items: [
                            {
                                xtype: 'editorgrid',
                                store: 'constructsStore',
                                height: 300,
                                region: 'center',
                                split: true,
                                stripeRows: true,
                                ref: '../../constructsEditorGrid',
                                id: 'constructsEditorGrid',
                                selModel: new Ext.grid.RowSelectionModel({
                                    singleSelect: true
                                }),
                                columns: [
                                    {
                                        xtype: 'numbercolumn',
                                        header: 'Serial Number',
                                        sortable: true,
                                        width: 100,
                                        align: 'left',
                                        dataIndex: 'identifier',
                                        editable: false,
                                        format: 0,
                                        id: 'identifierColumn',
                                        editor: {
                                            xtype: 'numberfield'
                                        }
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        header: 'Status',
                                        sortable: true,
                                        width: 100,
                                        dataIndex: 'status',
                                        editable: false,
                                        editor: {
                                            xtype: 'textfield'
                                        }
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'description',
                                        header: 'Description',
                                        sortable: true,
                                        width: 650,
                                        id: 'descripColumn',
                                        editor: {
                                            xtype: 'textfield'
                                        }
                                    }
                                ]
                            },
                            {
                                xtype: 'textarea',
                                region: 'south',
                                height: 200,
                                split: true,
                                style: '{font-family: \'courier\' }',
                                readOnly: true,
                                ref: '../../constructTextArea',
                                id: 'constructTextArea'
                            }
                        ],
                        tbar: {
                            xtype: 'toolbar',
                            autoHeight: true,
                            ref: '../../constructsToolbar',
                            id: 'constructsToolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'CSV',
                                    ref: '../../../constructsCSVButton',
                                    id: 'constructsCSVButton'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'BIOFAB',
                                    disabled: true,
                                    ref: '../../../constructsToDBButton',
                                    id: 'constructsToDBButton'
                                }
                            ]
                        }
                    }
                ]
            },
            {
                xtype: 'panel',
                title: 'Feedback',
                region: 'south',
                split: true,
                height: 150,
                layout: 'fit',
                ref: 'assemblerSouthPanel',
                id: 'southPanel',
                items: [
                    {
                        xtype: 'textarea',
                        readOnly: true,
                        emptyText: '',
                        ref: '../feedbackTextArea',
                        id: 'feedbackTextArea'
                    }
                ]
            }
        ];
        AssemblerPanelUi.superclass.initComponent.call(this);
    }
});
