/*
 * File: SeqCheckResultStore.js
 * Date: Fri Feb 04 2011 02:39:54 GMT-0800 (PST)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

SeqCheckResultStore = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        SeqCheckResultStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'seqCheckResultStore'
        }, cfg));
    }
});
new SeqCheckResultStore();