/*
 * File: SeqCheckerPanel.ui.js
 * Date: Fri Feb 04 2011 02:39:54 GMT-0800 (PST)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

SeqCheckerPanelUi = Ext.extend(Ext.TabPanel, {
    activeTab: 1,
    title: 'Sequence Checker',
    closable: true,
    id: 'seqCheckerPanel',
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                title: 'Input',
                layout: 'border',
                ref: 'seqCheckInputPanel',
                id: 'seqCheckInputPanel',
                items: [
                    {
                        xtype: 'editorgrid',
                        title: 'Mapping',
                        store: 'seqCheckMappingStore',
                        width: 400,
                        region: 'center',
                        stripeRows: true,
                        columnLines: true,
                        ref: '../mappingGridPanel',
                        id: 'mappingGridPanel',
                        columns: [
                            {
                                xtype: 'gridcolumn',
                                dataIndex: 'constructID',
                                header: 'Construct',
                                sortable: true,
                                width: 150,
                                editor: {
                                    xtype: 'textfield'
                                }
                            },
                            {
                                xtype: 'gridcolumn',
                                header: 'Clone',
                                sortable: true,
                                width: 100,
                                dataIndex: 'clone',
                                editor: {
                                    xtype: 'textfield'
                                }
                            },
                            {
                                xtype: 'gridcolumn',
                                header: 'Well',
                                sortable: true,
                                width: 100,
                                dataIndex: 'well',
                                editor: {
                                    xtype: 'textfield'
                                }
                            },
                            {
                                xtype: 'gridcolumn',
                                header: 'Trace',
                                sortable: true,
                                width: 300,
                                dataIndex: 'traceFileName',
                                editor: {
                                    xtype: 'textfield'
                                }
                            }
                        ]
                    },
                    {
                        xtype: 'editorgrid',
                        title: 'Boundaries',
                        store: 'startStopStore',
                        width: 250,
                        columnLines: true,
                        stripeRows: true,
                        region: 'east',
                        ref: '../startStopEditorGrid',
                        id: 'startStopEditorGrid',
                        columns: [
                            {
                                xtype: 'gridcolumn',
                                dataIndex: 'start',
                                header: 'Start',
                                sortable: true,
                                width: 120,
                                align: 'left',
                                editor: {
                                    xtype: 'textfield'
                                }
                            },
                            {
                                xtype: 'gridcolumn',
                                header: 'Stop',
                                sortable: true,
                                width: 120,
                                editor: {
                                    xtype: 'textfield'
                                }
                            }
                        ],
                        bbar: {
                            xtype: 'toolbar',
                            id: 'startStopToolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    text: '+',
                                    width: 20,
                                    ref: '../../../addStartStopButton',
                                    id: 'addStartStopButton'
                                },
                                {
                                    xtype: 'button',
                                    text: '-',
                                    width: 20,
                                    ref: '../../../deleteStartStopButton',
                                    id: 'deleteStartStopButton'
                                }
                            ]
                        }
                    }
                ],
                tbar: {
                    xtype: 'toolbar',
                    ref: '../seqCheckInputToolbar',
                    id: 'seqCheckInputToolbar',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Load Mapping',
                            ref: '../../loadMappingButton',
                            id: 'loadMappingButton'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            text: 'Check',
                            ref: '../../seqCheckButton',
                            id: 'seqCheckButton'
                        }
                    ]
                }
            },
            {
                xtype: 'panel',
                title: 'Output',
                layout: 'border',
                ref: 'seqCheckOutputPanel',
                id: 'seqCheckOutputPanel',
                tbar: {
                    xtype: 'toolbar',
                    ref: '../seqCheckOutputToolbar',
                    id: 'seqCheckOutputToolbar',
                    items: [
                        {
                            xtype: 'button',
                            text: 'BIOFAB',
                            ref: '../../seqCheckBiofabButton',
                            id: 'seqCheckBiofabButton'
                        }
                    ]
                },
                items: [
                    {
                        xtype: 'panel',
                        title: 'Alignment',
                        region: 'south',
                        split: true,
                        height: 300,
                        id: 'seqCheckAlignPanel'
                    },
                    {
                        xtype: 'container',
                        region: 'center',
                        layout: 'border',
                        split: true,
                        items: [
                            {
                                xtype: 'grid',
                                title: 'Constructs',
                                store: 'seqCheckResultStore',
                                width: 300,
                                region: 'west',
                                split: true,
                                columns: [
                                    {
                                        xtype: 'booleancolumn',
                                        header: 'Status',
                                        sortable: true,
                                        width: 100,
                                        trueText: 'Good',
                                        falseText: 'Bad',
                                        dataIndex: 'status'
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'constructID',
                                        header: 'Construct',
                                        sortable: true,
                                        width: 200,
                                        editable: false
                                    }
                                ]
                            },
                            {
                                xtype: 'grid',
                                title: 'Clones',
                                store: 'seqCheckResultStore',
                                flex: 1,
                                region: 'center',
                                width: 300,
                                split: true,
                                columns: [
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'string',
                                        header: 'Column',
                                        sortable: true,
                                        width: 100
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        dataIndex: 'number',
                                        header: 'Column',
                                        sortable: true,
                                        width: 100,
                                        align: 'right'
                                    },
                                    {
                                        xtype: 'datecolumn',
                                        dataIndex: 'date',
                                        header: 'Column',
                                        sortable: true,
                                        width: 100
                                    },
                                    {
                                        xtype: 'booleancolumn',
                                        dataIndex: 'bool',
                                        header: 'Column',
                                        sortable: true,
                                        width: 100
                                    }
                                ]
                            },
                            {
                                xtype: 'grid',
                                title: 'Errors',
                                store: 'seqCheckResultStore',
                                region: 'east',
                                width: 300,
                                split: true,
                                columns: [
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'string',
                                        header: 'Column',
                                        sortable: true,
                                        width: 100
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        dataIndex: 'number',
                                        header: 'Column',
                                        sortable: true,
                                        width: 100,
                                        align: 'right'
                                    },
                                    {
                                        xtype: 'datecolumn',
                                        dataIndex: 'date',
                                        header: 'Column',
                                        sortable: true,
                                        width: 100
                                    },
                                    {
                                        xtype: 'booleancolumn',
                                        dataIndex: 'bool',
                                        header: 'Column',
                                        sortable: true,
                                        width: 100
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ];
        SeqCheckerPanelUi.superclass.initComponent.call(this);
    }
});
