/*
 * File: AbstractPartStore.js
 * Date: Thu Oct 14 2010 05:36:46 GMT-0700 (PDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

AbstractPartStore = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        AbstractPartStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'AbstractPartStore',
            root: 'abstractparts',
            url: DATA_DIR + '/abstractparts.json',
            autoLoad: true,
            fields: [
                {
                    name: 'id',
                    type: 'string'
                },
                {
                    name: 'description',
                    type: 'string'
                },
                {
                    name: 'sequence',
                    type: 'string'
                },
                {
                    name: 'type',
                    type: 'string'
                },
                {
                    name: 'biofunction'
                }
            ]
        }, cfg));
    }
});
new AbstractPartStore();