/*
 * File: PilotProjectPanel.ui.js
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file was manually exported.
 */

PilotProjectPanelUi = Ext.extend(Ext.Panel, {
    title: 'Pilot Project',
    layout: 'absolute',
    tpl: '',
    closable: true,
    autoScroll: true,
    id: 'pilotProjectPanel',
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                title: 'Pilot Project Collection',
                height: 800,
                width: 600,
                layout: 'border',
                itemId: 'centerPanel',
                x: 25,
                y: 25,
                ref: 'centerPanelRef',
                floating: false,
                shadowOffset: 6,
                items: [
                    {
                        xtype: 'panel',
                        layout: 'fit',
                        region: 'center',
                        split: true,
                        height:200,
                        items: [
                            {
                                xtype: 'textarea',
                                itemId: 'collectionTextArea',
                                ref: '../../collectionTextAreaRef'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        title: 'Performance',
                        layout: 'fit',
                        region: 'south',
                        height: 600,
                        split: true,
                        id: 'collectionPerformancePanel',
                        items: [
                            {
                                xtype: 'tabpanel',
                                activeTab: 0,
                                id: 'collectionPerformanceTabPanel',
                                items: [
                                    {
                                        xtype: 'panel',
                                        title: 'GFP Expression',
                                        layout: 'absolute',
                                        html: '<img src="./data/heatmap_pilot_project_gfp.jpg" width="500" height="500">'
                                    },
                                    {
                                        xtype: 'panel',
                                        title: 'RFP Expression',
                                        layout: 'absolute',
                                        html: '<img src="./data/heatmap_pilot_project_rfp.jpg" width="500" height="500">'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ];
        PilotProjectPanelUi.superclass.initComponent.call(this);
    }
});
